use_frameworks!

target 'CBAlert_Example' do
  pod 'CBAlert', :path => '../'

  target 'CBAlert_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'

  end
end
